# Generated by Django 3.0.8 on 2020-07-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(default='', max_length=200)),
                ('numbers', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
