# Generated by Django 3.0.8 on 2020-07-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cn', models.CharField(default='', max_length=100)),
                ('name_en', models.CharField(default='', max_length=100)),
                ('publish_y', models.DateField()),
                ('poster', models.CharField(default='', max_length=100)),
                ('director', models.CharField(default='', max_length=20)),
                ('starring', models.CharField(default='', max_length=100)),
                ('tags', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='album_path',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='album',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='album',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='numbers',
            field=models.IntegerField(default=0),
        ),
    ]
