# Generated by Django 3.0.8 on 2020-07-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_auto_20200721_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='path',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='publish_y',
            field=models.IntegerField(default=1900),
        ),
    ]
