# Generated by Django 3.0.8 on 2020-07-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_auto_20200721_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.FilePathField(path='D://PersonalProject//Aniku_django//templates//img'),
        ),
    ]
