# Generated by Django 3.0.8 on 2020-07-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_auto_20200721_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name_en',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='path',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.FilePathField(null=True, path='D://PersonalProject//Aniku_django//templates'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='publish_y',
            field=models.IntegerField(default=1900, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='starring',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
