# Generated by Django 3.0.8 on 2020-07-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_auto_20200721_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='path',
            field=models.FilePathField(allow_folders=True, default='', path='D://PersonalProject//Aniku_django//templates//img'),
        ),
    ]
