# Generated by Django 3.0.8 on 2020-07-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0009_auto_20200721_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cn', models.CharField(default='', max_length=100)),
                ('name_en', models.CharField(default='', max_length=100)),
                ('publish_y', models.IntegerField(default=1900, null=True)),
                ('seasons', models.IntegerField(default=1, null=True)),
                ('season', models.IntegerField(default=1, null=True)),
                ('part', models.IntegerField(default=1)),
                ('poster', models.FileField(null=True, upload_to='')),
                ('director', models.CharField(blank=True, default='', max_length=20)),
                ('staff', models.CharField(blank=True, default='', max_length=100)),
                ('tags', models.CharField(blank=True, default='', max_length=100)),
                ('path', models.FilePathField(allow_folders=True, default='', path='D://PersonalProject//Aniku_django//templates//img')),
                ('byte', models.FloatField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='starring',
            new_name='staff',
        ),
        migrations.AddField(
            model_name='movie',
            name='byte',
            field=models.FloatField(default=0),
        ),
    ]
