# Generated by Django 3.0.8 on 2020-08-01 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0011_auto_20200731_1610'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
    ]
