# Generated by Django 3.0.8 on 2020-08-01 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0012_delete_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='path',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster',
        ),
    ]
