# Generated by Django 3.0.8 on 2020-08-01 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0014_auto_20200801_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animation',
            old_name='byte',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='byte',
            new_name='size',
        ),
    ]
