# Generated by Django 3.0.8 on 2020-08-01 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0015_auto_20200801_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='staff',
            new_name='starring',
        ),
    ]
