# Generated by Django 3.0.8 on 2020-08-01 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0017_auto_20200801_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tv',
            fields=[
                ('movie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='anime.Movie')),
                ('seasons', models.IntegerField(default=1, null=True)),
                ('season', models.IntegerField(default=1, null=True)),
                ('parts', models.IntegerField(default=1)),
                ('part', models.IntegerField(default=1)),
            ],
            bases=('anime.movie',),
        ),
        migrations.AddField(
            model_name='movie',
            name='path',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='animation',
            name='director',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
