# Generated by Django 3.0.8 on 2020-08-03 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0019_auto_20200803_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animation',
            old_name='db_id',
            new_name='douban_id',
        ),
    ]
