# Generated by Django 3.0.8 on 2020-08-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0020_auto_20200803_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
